name: resellah_landing_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  intl: ^0.20.1
  http: ^1.3.0
  logger: ^2.5.0
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  curved_navigation_bar: ^1.0.6
  carousel_slider: ^5.0.0
  firebase_core: ^2.27.1
  firebase_analytics: ^10.8.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/on_boarding_images/
    - assets/images/carousel_images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf 
          style: italic
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
    - family: Agbalumo
      fonts:
        - asset: assets/fonts/Agbalumo-Regular.ttf



